### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [sellis7/splurtyMcBean#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by sellis7** [comment]
You know, you mentioning things like that - and also some things brought to my attention by Carleton (my mentor) - are making me realize I need to step up my game! \o/ I really appreciate all the comments, suggestions and advice... after years in fine art studies, I have no issues with receiving constructive criticism. :)
Anyways... I was getting at the fact that I knew of using the meta tag, though I find I'm now a bit fuzzy with some of it. Enough has changed that some things I was told to apply are not necessary now with Rails (as Carleton was telling me - like HTML shims not really being needed), so I'm not sure when to apply them - and (due to the unfamiliar folder heirarchy of Rails) where. I really hope this all starts "sticking" and becomes second-nature to me soon! 
I applied what I think you were referencing, and also noticed that my font errors disappeared that had surfaced in the developer tools... was that related? So much to learn! :D

**Comment by kenmazaika** [comment]
Hi Sherilyn -

Looks like you may have done a few other (awesome tweaks), but the mobile meta tag I mentioned looks like it's not in `application.html.erb`.  Take a look at this video I made a _very_ long time ago:
https://vimeo.com/75718091

Hope this helps.

Cheers,
Ken

**Comment by sellis7** [comment]
:facepalm:

Bwahahahahaha! I had done that... but I forgot to push my code to Git. Sooooo YEAH. You _totally_ could see it, right? (omg I'm so embarrassed) That's now the 1st time you have experienced my "blonde" – I had a moment with Carleton before I actually "met" him via Skype. My declaration is that since I'm a real (though dark) blonde, I'm allowed 1 moment a day... but I usually do better than that and have far less. ;)

Apologies for that, and thanks for your sage advice
– S

**Comment by kenmazaika** [comment]
Hehe!  No problems.  Your code looks solid now that I can see it! :) :+1:

**Comment by sellis7** [comment]
Thanks a ton!
